version: '2'
services:
  mysql:
      container_name: lobj-mysql
      #build: ./mysql
      image: lobj/mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_ROOT_HOST: '%'
        MYSQL_USER: longer
        MYSQL_PASSWORD: l124561
        #MYSQL_ALLOW_EMPTY_PASSWORD: 1
        #MYSQL_RANDOM_ROOT_PASSWORD: 0